// @ts-check
// Type definitions for Starnet game state.
// No runtime code — pure JSDoc @typedef declarations.
// Import in other files with: @typedef {import('./types.js').Foo} Foo

// ── String union types ────────────────────────────────────

/** @typedef {"hidden"|"revealed"|"accessible"} Visibility */
/** @typedef {"locked"|"compromised"|"owned"} AccessLevel */
/** @typedef {"green"|"yellow"|"red"} NodeAlertLevel */
/** @typedef {"green"|"yellow"|"red"|"trace"} GlobalAlertLevel */
/** @typedef {"fresh"|"worn"|"disclosed"} DecayState */
/** @typedef {"playing"|"ended"} GamePhase */
/** @typedef {"success"|"caught"} RunOutcome */
/** @typedef {"S"|"A"|"B"|"C"|"D"|"F"} Grade */
/** @typedef {"common"|"uncommon"|"rare"} Rarity */

// ── Leaf data shapes ──────────────────────────────────────

/**
 * A vulnerability on a node. Generated by exploits.js; may also be hand-crafted
 * in network data as staged vulnerabilities.
 * @typedef {{
 *   id: string,
 *   name: string,
 *   description: string,
 *   rarity: Rarity,
 *   patched: boolean,
 *   patchTurn: number|null,
 *   hidden: boolean,
 *   unlockedBy: string|null,
 * }} Vulnerability
 */

/**
 * A lootable item on a node.
 * @typedef {{
 *   id: string,
 *   typeId: string,
 *   name: string,
 *   description: string,
 *   cashValue: number,
 *   collected: boolean,
 *   isMission?: boolean,
 * }} Macguffin
 */

/**
 * An exploit card in the player's hand.
 * @typedef {{
 *   id: string,
 *   name: string,
 *   rarity: Rarity,
 *   quality: number,
 *   targetVulnTypes: string[],
 *   decayState: DecayState,
 *   usesRemaining: number,
 * }} ExploitCard
 */

/**
 * Result of resolveExploit(). levelChanged and partialBurn are added by state.js
 * after the initial result is constructed.
 * @typedef {{
 *   success: boolean,
 *   disclosed: boolean,
 *   successChance: number,
 *   roll: number,
 *   matchingVulns: Vulnerability[],
 *   flavor: string,
 *   levelChanged?: boolean,
 *   partialBurn?: boolean,
 * }} ExploitResult
 */

// ── Composite shapes ──────────────────────────────────────

/**
 * Per-node game state. All fields are managed exclusively through state.js mutations.
 * @typedef {{
 *   id: string,
 *   type: string,
 *   label: string,
 *   grade: Grade,
 *   visibility: Visibility,
 *   accessLevel: AccessLevel,
 *   alertState: NodeAlertLevel,
 *   probed: boolean,
 *   vulnerabilities: Vulnerability[],
 *   macguffins: Macguffin[],
 *   read: boolean,
 *   looted: boolean,
 *   eventForwardingDisabled?: boolean,
 *   rebooting: boolean,
 * }} NodeState
 */

/**
 * ICE entity state. Null when no ICE is defined for the network.
 * @typedef {{
 *   grade: Grade,
 *   residentNodeId: string,
 *   attentionNodeId: string,
 *   active: boolean,
 *   dwellTimerId: number|null,
 *   detectedAtNode: string|null,
 *   detectionCount: number,
 * }} IceState
 */

/**
 * @typedef {{
 *   cash: number,
 *   hand: ExploitCard[],
 * }} PlayerState
 */

/**
 * Tracks an in-progress exploit execution. Null when no exploit is running.
 * @typedef {{
 *   nodeId: string,
 *   exploitId: string,
 *   timerId: number,
 *   noiseTimerId: number,
 *   noiseTick: number,
 * }} ExecutingExploit
 */

/**
 * Tracks an in-progress probe scan. Null when no probe is running.
 * @typedef {{
 *   nodeId: string,
 *   timerId: number,
 * }} ActiveProbe
 */

/**
 * Tracks an in-progress read scan. Null when no read is running.
 * @typedef {{
 *   nodeId: string,
 *   timerId: number,
 * }} ActiveRead
 */

/**
 * @typedef {{
 *   targetMacguffinId: string,
 *   targetName: string,
 *   complete: boolean,
 * }} MissionState
 */

// ── Node type registry shapes ─────────────────────────────

/**
 * A grade-keyed numeric table (e.g. { S: 0.05, A: 0.15, ... }).
 * @typedef {Partial<Record<Grade, number>>} GradeNumberMap
 */

/**
 * Per-type combat modifier overrides. Any omitted key falls back to the
 * global default table in combat.js.
 * @typedef {{
 *   gradeModifier?:    GradeNumberMap,
 *   disclosureChance?: GradeNumberMap,
 *   patchLag?:         GradeNumberMap,
 * }} CombatConfig
 */

/**
 * Per-type vulnerability generation overrides. Any omitted key falls back to
 * the global VULN_CONFIG table in exploits.js.
 * @typedef {{
 *   count?:    Partial<Record<Grade, number[]>>,
 *   rarities?: Partial<Record<Grade, Rarity[]>>,
 * }} VulnConfig
 */

/**
 * Dependency-injection context passed to action execute() functions.
 * main.js constructs one instance at init, wiring each field to the
 * corresponding state mutator. Tests can pass mock contexts.
 * @typedef {{
 *   getState:      () => GameState,
 *   selectNode:    (nodeId: string) => void,
 *   deselectNode:  () => void,
 *   startProbe:    (nodeId: string) => void,
 *   cancelProbe:   () => void,
 *   startExploit:  (nodeId: string, exploitId: string) => void,
 *   cancelExploit: () => void,
 *   startRead:     (nodeId: string) => void,
 *   cancelRead:    () => void,
 *   lootNode:      (nodeId: string) => void,
 *   ejectIce:         () => void,
 *   rebootNode:       (nodeId: string) => void,
 *   jackOut:          () => void,
 *   reconfigureNode:     (nodeId: string) => void,
 *   cancelTrace:         () => void,
 *   openDarknetsStore:   () => void,
 * }} ActionContext
 */

/**
 * An action available on a node — rendered as a sidebar button and console action.
 * @typedef {{
 *   id:         string,
 *   label:      string,
 *   available:  (node: NodeState, state: GameState) => boolean,
 *   desc:       (node: NodeState, state: GameState) => string,
 *   execute?:   (node: NodeState, state: GameState, ctx: ActionContext, payload?: Object) => void,
 *   noSidebar?: boolean,
 * }} ActionDef
 */

/**
 * A composable behavior atom. Hooks receive a ctx object with game functions
 * injected by the dispatcher (dependency injection — atoms have no game imports).
 * @typedef {{
 *   id:              string,
 *   stateFields?:    Object,
 *   onInit?:         (node: NodeState, state: GameState, ctx: Object) => void,
 *   onOwned?:        (node: NodeState, state: GameState, ctx: Object) => void,
 *   onAlertRaised?:  (node: NodeState, state: GameState, ctx: Object) => void,
 *   onReconfigured?: (node: NodeState, state: GameState, ctx: Object) => void,
 * }} BehaviorAtom
 */

/**
 * Per-grade override for a node type. extraBehaviors/extraActions append to the
 * base list; behaviors/actions replace it entirely for that grade.
 * @typedef {{
 *   behaviors?:      string[],
 *   extraBehaviors?: string[],
 *   actions?:        ActionDef[],
 *   extraActions?:   ActionDef[],
 *   combatConfig?:   CombatConfig,
 *   vulnConfig?:     VulnConfig,
 * }} GradeOverride
 */

/**
 * A node type definition in the registry.
 * @typedef {{
 *   behaviors:      string[],
 *   actions:        ActionDef[],
 *   lootConfig?:    { count: number[] },
 *   combatConfig?:  CombatConfig,
 *   vulnConfig?:    VulnConfig,
 *   gateAccess?:    "probed"|"compromised"|"owned",
 *   gradeOverrides?: Partial<Record<Grade, GradeOverride>>,
 * }} NodeTypeDef
 */

// ── Top-level state ───────────────────────────────────────

/**
 * The complete game state. Managed exclusively through state.js.
 * Never mutate directly — always use exported state mutation functions.
 * @typedef {{
 *   seed: string,
 *   nodes: Object.<string, NodeState>,
 *   adjacency: Object.<string, string[]>,
 *   player: PlayerState,
 *   globalAlert: GlobalAlertLevel,
 *   traceSecondsRemaining: number|null,
 *   traceTimerId: number|null,
 *   selectedNodeId: string|null,
 *   phase: GamePhase,
 *   runOutcome: RunOutcome|null,
 *   isCheating: boolean,
 *   ice: IceState|null,
 *   lastDisturbedNodeId: string|null,
 *   mission: MissionState|null,
 *   executingExploit: ExecutingExploit|null,
 *   activeProbe: ActiveProbe|null,
 *   activeRead: ActiveRead|null,
 * }} GameState
 */

// ── Event payload types ───────────────────────────────────

/** @typedef {{ text: string, type: string }} LogEntryPayload */

/** @typedef {{ nodeId: string, label: string, unlocked?: boolean }} NodeRevealedPayload */
/** @typedef {{ nodeId: string, label: string }} NodeProbedPayload */
/** @typedef {{ nodeId: string, label: string, prev: AccessLevel, next: AccessLevel }} NodeAccessedPayload */
/** @typedef {{ nodeId: string, label: string, prev: NodeAlertLevel, next: NodeAlertLevel }} NodeAlertRaisedPayload */
/** @typedef {{ nodeId: string, label: string, macguffinCount: number }} NodeReadPayload */
/** @typedef {{ nodeId: string, label: string, items: number, total: number }} NodeLootedPayload */
/** @typedef {{ nodeId: string, label: string }} NodeReconfiguredPayload */
/** @typedef {{ nodeId: string, label: string, durationMs: number }} NodeRebootingPayload */
/** @typedef {{ nodeId: string, label: string }} NodeRebootedPayload */

/** @typedef {{ nodeId: string, label: string, exploitName: string, flavor: string, roll: number, successChance: number, matchingVulns: Vulnerability[] }} ExploitSuccessPayload */
/** @typedef {{ nodeId: string, label: string, exploitName: string, flavor: string, roll: number, successChance: number, matchingVulns: Vulnerability[] }} ExploitFailurePayload */
/** @typedef {{ exploitName: string }} ExploitDisclosedPayload */
/** @typedef {{ exploitName: string, usesRemaining: number }} ExploitPartialBurnPayload */
/** @typedef {{ nodeId: string, label: string }} ExploitSurfacePayload */
/** @typedef {{ nodeId: string, label: string, exploitName: string, durationMs: number }} ExploitStartedPayload */
/** @typedef {{ nodeId: string, exploitName: string }} ExploitInterruptedPayload */

/** @typedef {{ nodeId: string, label: string, durationMs: number }} ProbeScanStartedPayload */
/** @typedef {{ nodeId: string, label: string }} ProbeScanCancelledPayload */

/** @typedef {{ nodeId: string, label: string, durationMs: number }} ReadScanStartedPayload */
/** @typedef {{ nodeId: string, label: string }} ReadScanCancelledPayload */

/** @typedef {{ prev: GlobalAlertLevel, next: GlobalAlertLevel }} AlertGlobalRaisedPayload */
/** @typedef {{ seconds: number }} AlertTraceStartedPayload */
/** @typedef {{ fromNodeId: string, fromLabel: string, toNodeId: string, toLabel: string }} AlertPropagatedPayload */

/** @typedef {{ fromId: string, toId: string, fromLabel: string, toLabel: string, fromVisible: boolean, toVisible: boolean }} IceMovedPayload */
/** @typedef {{ nodeId: string, label: string, dwellMs: number }} IceDetectPendingPayload */
/** @typedef {{ nodeId: string, label: string }} IceDetectedPayload */
/** @typedef {{ fromId: string, toId: string }} IceEjectedPayload */
/** @typedef {{ residentNodeId: string, residentLabel: string }} IceRebootedPayload */

/** @typedef {{ targetName: string }} MissionStartedPayload */
/** @typedef {{ targetName: string }} MissionCompletePayload */

/** @typedef {{ outcome: RunOutcome }} RunEndedPayload */
/** @typedef {{ state: GameState }} RunStartedPayload */

// Required to make this file a proper ES module so @typedef imports work.
export {};
