// @ts-check
// Type definitions for Starnet game state.
// No runtime code — pure JSDoc @typedef declarations.
// Import in other files with: @typedef {import('./types.js').Foo} Foo

// ── String union types ────────────────────────────────────

/** @typedef {"hidden"|"revealed"|"accessible"} Visibility */
/** @typedef {"locked"|"owned"} AccessLevel */
/** @typedef {"green"|"yellow"|"red"} NodeAlertLevel */
/** @typedef {"green"|"yellow"|"red"|"trace"} GlobalAlertLevel */
/** @typedef {"playing"|"ended"} GamePhase */
/** @typedef {"success"|"caught"|"burned"|"bricked"} RunOutcome */
/** @typedef {"S"|"A"|"B"|"C"|"D"|"F"} Grade */
/** @typedef {"common"|"uncommon"|"rare"} Rarity */

// ── Leaf data shapes ──────────────────────────────────────

/**
 * A vulnerability on a node. Generated by exploits.js; may also be hand-crafted
 * in network data as staged vulnerabilities.
 * @typedef {{
 *   id: string,
 *   name: string,
 *   description: string,
 *   rarity: Rarity,
 *   patched: boolean,
 *   patchTurn: number|null,
 *   hidden: boolean,
 *   unlockedBy: string|null,
 * }} Vulnerability
 */

/**
 * A lootable item on a node.
 * @typedef {{
 *   id: string,
 *   typeId: string,
 *   name: string,
 *   description: string,
 *   cashValue: number,
 *   collected: boolean,
 *   isMission?: boolean,
 * }} Macguffin
 */

/**
 * A disposable exploit round in the player's hoard (E1 exploit economy).
 * Rounds are anonymous ammunition identified by a terse hex tag. Rare rounds
 * carry multiple exploit types; uncommon carry 2; common carry 1.
 * @typedef {{
 *   id: string,
 *   rarity: Rarity,
 *   types: string[],
 *   disclosed: boolean,
 * }} ExploitRound
 */

/**
 * A piece of smash-tooling gear the player can own and equip (E2 Phase 1).
 * Owned ids live in StarnetProfile.gear; the equipped subset for a run lives in
 * PlayerState.loadout. See js/core/gear.js for the full registry and resolver.
 * @typedef {{ id: string, name: string, kind: "select"|"heat"|"bite", price: number, desc: string }} Gear
 */

// ── Composite shapes ──────────────────────────────────────

/**
 * Per-node game state. Core fields are listed here; trait-provided attributes
 * (probing, exploiting, reading, looting, activeExploitId, mining, mineAttempts,
 * mineExhausted, etc.) are dynamic and accessed via index signature.
 * `coherence` and `coherenceMax` are optional fields added by the E1 exploit-hoard
 * combat rework — wired in a later phase; absent on nodes not yet participating.
 * @typedef {{
 *   id: string,
 *   type: string,
 *   label: string,
 *   visibility: string,
 *   coherence?: number,
 *   coherenceMax?: number,
 *   [key: string]: any,
 * }} NodeState
 */

/**
 * A single ICE entity in the reinvented multi-instance model. For session 1
 * the collection holds exactly one instance per network, ported from the
 * pre-reinvention singleton. Additional fields (triggers, effects, etc.)
 * are introduced in later sessions.
 *
 * Migration note: residentNodeId is deprecated in favor of hostNodeId;
 * both are kept for now during the transition.
 *
 * @typedef {{
 *   id: string,
 *   typeId: string,
 *   hostNodeId: string,
 *   residentNodeId?: string,
 *   attentionNodeId: string,
 *   active: boolean,
 *   enabled: boolean,
 *   grade: Grade,
 *   focus: "stationary" | "roaming",
 *   behaviorPattern: string,
 *   dwellTimerId: number|null,
 *   moveTimerId: number|null,
 *   detectedAtNode: string|null,
 *   detectionCount: number,
 * }} IceInstance
 */

/**
 * @deprecated Use IceInstance. Retained as a type alias for callers
 * mid-migration; will be removed in a future session.
 * @typedef {IceInstance} IceState
 */

/**
 * Collection of ICE instances keyed by instance id.
 * @typedef {{
 *   instances: Object.<string, IceInstance>,
 * }} IceCollection
 */

/**
 * @typedef {{
 *   cash: number,
 *   hoard: ExploitRound[],
 *   loadout: string[],
 *   health: { current: number, max: number },
 *   deckIntegrity: { current: number, max: number },
 *   capturedCredentials: string[],
 * }} PlayerState
 */

/**
 * Persistent cross-run player profile. Lives OUTSIDE GameState (in localStorage
 * via js/ui/profile-store.js), so it survives resetGame between runs. Model and
 * mutations are in js/core/profile.
 * `hoard` is the persistent carry-all ammunition (E1 hoard cutover). The legacy
 * card `inventory` was removed in the Phase 9 sweep once every consumer was
 * repointed to the hoard.
 * `gear` is the player's owned gear ids (E2 Phase 1). Empty by default; store-bought
 * (wired in Phase 3). Loadout (equipped subset) lives in PlayerState for the run.
 * @typedef {{
 *   version: number,
 *   bank: number,
 *   hoard: ExploitRound[],
 *   gear: string[],
 *   _hubVisits: number,
 * }} StarnetProfile
 */

/**
 * Tracks an in-progress exploit execution. Null when no exploit is running.
 * @typedef {{
 *   nodeId: string,
 *   exploitId: string,
 *   timerId: number,
 *   noiseTimerId: number,
 *   noiseTick: number,
 * }} ExecutingExploit
 */

/**
 * Tracks an in-progress probe scan. Null when no probe is running.
 * @typedef {{
 *   nodeId: string,
 *   timerId: number,
 * }} ActiveProbe
 */

/**
 * Tracks an in-progress read scan. Null when no read is running.
 * @typedef {{
 *   nodeId: string,
 *   timerId: number,
 * }} ActiveRead
 */

/**
 * Tracks an in-progress loot extraction. Null when no loot is running.
 * @typedef {{
 *   nodeId: string,
 *   timerId: number,
 * }} ActiveLoot
 */

/**
 * @typedef {{
 *   targetMacguffinId: string,
 *   targetName: string,
 *   complete: boolean,
 * }} MissionState
 */

// ── Node type registry shapes ─────────────────────────────

/**
 * A grade-keyed numeric table (e.g. { S: 0.05, A: 0.15, ... }).
 * @typedef {Partial<Record<Grade, number>>} GradeNumberMap
 */

/**
 * Per-type combat modifier overrides. Any omitted key falls back to the
 * global default table in combat.js.
 * @typedef {{
 *   gradeModifier?:    GradeNumberMap,
 *   disclosureChance?: GradeNumberMap,
 *   patchLag?:         GradeNumberMap,
 * }} CombatConfig
 */

/**
 * Per-type vulnerability generation overrides. Any omitted key falls back to
 * the global VULN_CONFIG table in exploits.js.
 * @typedef {{
 *   count?:    Partial<Record<Grade, number[]>>,
 *   rarities?: Partial<Record<Grade, Rarity[]>>,
 * }} VulnConfig
 */

/**
 * Dependency-injection context passed to action execute() functions.
 * main.js constructs one instance at init, wiring each field to the
 * corresponding state mutator. Tests can pass mock contexts.
 * Action context for the dispatcher — only contains actions not handled by the
 * graph's trait-based action system. Most game actions (probe, exploit, read,
 * loot, reboot, reconfigure) are now graph-native via timed-action operators.
 * @typedef {{
 *   getState:          () => GameState,
 *   selectNode:        (nodeId: string) => void,
 *   deselectNode:      () => void,
 *   ejectIce:          () => void,
 *   jackOut:            () => void,
 *   cancelTrace:       () => void,
 *   openDarknetsStore: () => void,
 * }} ActionContext
 */

/**
 * An action available on a node — rendered as a sidebar button and console action.
 * @typedef {{
 *   id:         string,
 *   label:      string,
 *   available:  (node: NodeState, state: GameState) => boolean,
 *   desc:       (node: NodeState, state: GameState) => string,
 *   execute?:   (node: NodeState, state: GameState, ctx: ActionContext, payload?: Object) => void,
 *   noSidebar?: boolean,
 *   followup?:  import('./node-graph/types.js').FollowupStep,
 * }} ActionDef
 */

/**
 * A composable behavior atom. Hooks receive a ctx object with game functions
 * injected by the dispatcher (dependency injection — atoms have no game imports).
 * @typedef {{
 *   id:              string,
 *   stateFields?:    Object,
 *   onInit?:         (node: NodeState, state: GameState, ctx: Object) => void,
 *   onOwned?:        (node: NodeState, state: GameState, ctx: Object) => void,
 *   onAlertRaised?:  (node: NodeState, state: GameState, ctx: Object) => void,
 *   onReconfigured?: (node: NodeState, state: GameState, ctx: Object) => void,
 * }} BehaviorAtom
 */

/**
 * Per-grade override for a node type. extraBehaviors/extraActions append to the
 * base list; behaviors/actions replace it entirely for that grade.
 * @typedef {{
 *   behaviors?:      string[],
 *   extraBehaviors?: string[],
 *   actions?:        ActionDef[],
 *   extraActions?:   ActionDef[],
 *   combatConfig?:   CombatConfig,
 *   vulnConfig?:     VulnConfig,
 * }} GradeOverride
 */

/**
 * A node type definition in the registry.
 * @typedef {{
 *   behaviors:      string[],
 *   actions:        ActionDef[],
 *   lootConfig?:    { count: number[] },
 *   combatConfig?:  CombatConfig,
 *   vulnConfig?:    VulnConfig,
 *   gateAccess?:    "probed"|"owned",
 *   gradeOverrides?: Partial<Record<Grade, GradeOverride>>,
 * }} NodeTypeDef
 */

// ── Flow substrate ────────────────────────────────────────

/**
 * A typed data flow traversing the edge from `from` to `to`. First-class,
 * serializable state (authored in a network's `meta.flows`) — edges themselves
 * are not serializable. "encrypted" is a render/concealment state, not a type.
 * @typedef {{
 *   from: string,
 *   to: string,
 *   type: ('money'|'data'|'audit'|'control'|'credential'),
 *   rate: number,
 *   encrypted?: boolean,
 *   key?: string,
 *   revealed?: boolean,
 * }} Flow
 */

/**
 * A progressive, abortable player operation that advances over ticks and may affect nodes beyond
 * its origin (js/core/processes.js). Generic seam: `type` selects the registered handler; the rest
 * is that handler's serializable in-flight state. `nodeId` is the origin (drives busy/abort). SWEEP
 * is the first client; parallel-XPLOIT etc. plug into the same registry.
 * @typedef {{ id: number, type: string, nodeId: string, [k: string]: any }} Process
 */

// ── Top-level state ───────────────────────────────────────

/**
 * The complete game state. Managed exclusively through state.js.
 * Never mutate directly — always use exported state mutation functions.
 * @typedef {{
 *   seed: string,
 *   moneyCost: Grade,
 *   nodes: Object.<string, NodeState>,
 *   adjacency: Object.<string, string[]>,
 *   flows: Flow[],
 *   heat: number,
 *   heatDecayTimerId: number|null,
 *   processes: Process[],
 *   player: PlayerState,
 *   globalAlert: GlobalAlertLevel,
 *   traceSecondsRemaining: number|null,
 *   traceTimerId: number|null,
 *   selectedNodeId: string|null,
 *   phase: GamePhase,
 *   runOutcome: RunOutcome|null,
 *   isCheating: boolean,
 *   ice: IceCollection|null,
 *   lastDisturbedNodeId: string|null,
 *   mission: MissionState|null,
 *   ui: { menuOpen: boolean },
 *   nodeGraph?: any,
 *   spec?: Object|null,
 * }} GameState
 */

// ── Event payload types ───────────────────────────────────

/** @typedef {{ text: string, type: string }} LogEntryPayload */

/** @typedef {{ nodeId: string, label: string, unlocked?: boolean }} NodeRevealedPayload */
/** @typedef {{ nodeId: string, label: string }} NodeProbedPayload */
/** @typedef {{ nodeId: string, label: string, prev: AccessLevel, next: AccessLevel }} NodeAccessedPayload */
/** @typedef {{ nodeId: string, label: string, prev: NodeAlertLevel, next: NodeAlertLevel }} NodeAlertRaisedPayload */
/** @typedef {{ nodeId: string, label: string, macguffinCount: number }} NodeReadPayload */
/** @typedef {{ nodeId: string, label: string, items: number, total: number }} NodeLootedPayload */
/** @typedef {{ nodeId: string, label: string }} NodeReconfiguredPayload */
/** @typedef {{ nodeId: string, label: string, durationMs: number }} NodeRebootingPayload */
/** @typedef {{ nodeId: string, label: string }} NodeRebootedPayload */

/** @typedef {{ nodeId: string, label: string, exploitName: string, flavor: string, roll: number, successChance: number, matchingVulns: Vulnerability[] }} ExploitSuccessPayload */
/** @typedef {{ nodeId: string, label: string, exploitName: string, flavor: string, roll: number, successChance: number, matchingVulns: Vulnerability[] }} ExploitFailurePayload */
/** @typedef {{ exploitName: string }} ExploitDisclosedPayload */
/** @typedef {{ exploitName: string, usesRemaining: number }} ExploitPartialBurnPayload */
/** @typedef {{ nodeId: string, label: string }} ExploitSurfacePayload */
/** @typedef {{ nodeId: string, label: string, exploitName: string, durationMs: number }} ExploitStartedPayload */
/** @typedef {{ nodeId: string, exploitName: string }} ExploitInterruptedPayload */

/** @typedef {{ nodeId: string, label: string, durationMs: number }} ProbeScanStartedPayload */
/** @typedef {{ nodeId: string, label: string }} ProbeScanCancelledPayload */

/** @typedef {{ nodeId: string, label: string, durationMs: number }} ReadScanStartedPayload */
/** @typedef {{ nodeId: string, label: string }} ReadScanCancelledPayload */

/** @typedef {{ nodeId: string, label: string, durationMs: number }} LootExtractStartedPayload */
/** @typedef {{ nodeId: string, label: string }} LootExtractCancelledPayload */

/** @typedef {{ prev: GlobalAlertLevel, next: GlobalAlertLevel }} AlertGlobalRaisedPayload */
/** @typedef {{ seconds: number }} AlertTraceStartedPayload */
/** @typedef {{ fromNodeId: string, fromLabel: string, toNodeId: string, toLabel: string }} AlertPropagatedPayload */

/** @typedef {{ fromId: string, toId: string, fromLabel: string, toLabel: string, fromVisible: boolean, toVisible: boolean }} IceMovedPayload */
/** @typedef {{ nodeId: string, label: string, dwellMs: number }} IceDetectPendingPayload */
/** @typedef {{ nodeId: string, label: string }} IceDetectedPayload */
/** @typedef {{ fromId: string, toId: string }} IceEjectedPayload */
/** @typedef {{ residentNodeId: string, residentLabel: string }} IceRebootedPayload */

/** @typedef {{ targetName: string }} MissionStartedPayload */
/** @typedef {{ targetName: string }} MissionCompletePayload */

/** @typedef {{ outcome: RunOutcome }} RunEndedPayload */
/** @typedef {{ state: GameState }} RunStartedPayload */

// Required to make this file a proper ES module so @typedef imports work.
export {};
