// Starnet — strudel.cc PREBAKE  (one-paste authoring block)
// =====================================================================================
// AUTO-GENERATED by `make gen-prebake` from audio-content/soundfonts/manifest.js.
// Do not edit by hand — edit the manifest or scripts/gen-prebake.js instead.
//
// Paste this ONCE into strudel.cc → Settings → "prebake" (the script that runs before every
// song). It sets up BOTH halves of the game's sound world so a Starnet song copied straight out
// of the repo plays UNCHANGED in the editor:
//
//   1. Instruments — the game's soundfont presets per font (gus_*, msg_*, …).
//      Each is a DISTINCT set, NOT strudel's built-in gm_*; do not substitute.
//   2. Signals — the live game variables `gameProgress` / `gameThreat`, stubbed here as sliders
//      you drag to hear a song react.
//
// In the game these same names are provided by the engine (js/audio/strudel/soundfont.js registers
// the identical presets; js/audio/strudel/signal-bridge.js injects the same signals), so song files
// carry no setup of their own — this prebake is the editor-side mirror of that contract.

// ── 0. Firefox soundfont-release fix ──
// Firefox does not implement AudioParam.cancelAndHoldAtTime, which the SF2 player calls on every
// soundfont note-off. Without it note-offs throw in Firefox → soundfont voices never release (notes
// ring forever, voices pile up). Polyfill it (hold-current-value) before anything plays. No-op in
// Chrome, and no-op in the game (the engine's runtime installs the same shim). Mirrors runtime.js.
if (typeof AudioParam !== 'undefined' && typeof AudioParam.prototype.cancelAndHoldAtTime !== 'function') {
  AudioParam.prototype.cancelAndHoldAtTime = function (t) {
    const held = this.value;
    try { this.cancelScheduledValues(t); } catch (_) { /* ignore */ }
    try { this.setValueAtTime(held, t); } catch (_) { /* ignore */ }
    return this;
  };
}

// ── 1. Instruments: register every font's presets under its prefix ──
// Loads each full authoring SF2 (CORS-enabled host) so the sound set is byte-identical to what
// composers work with. The naming (sanitize + dedup) and the note trigger MIRROR
// js/audio/strudel/soundfont.js exactly; keep them in sync if that file changes.
// `fonts: []` lets strudel.cc's soundfont UI render the entry (it reads options.fonts.length);
// our trigger closes over `preset`, so the array itself is unused for audio.
async function registerSoundfont(url, prefix) {
  const sf = await loadSoundfont(url);
  const used = new Set();
  sf.presets.forEach((preset, i) => {
    const cleaned = String(preset.header?.name || '').toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
    let name = prefix + (cleaned || 'preset_' + i);
    if (used.has(name)) { const base = name; let n = 2; while (used.has(name)) name = base + '_' + n++; }
    used.add(name);
    registerSound(name, (time, value) => {
      // Route the voice into our own gain node and RETURN it so superdough applies its FX chain
      // (gain/room/lpf/pan/…) — it only wires effects onto the returned node, and bails on none.
      // sfumato's startPresetNote self-connects to ctx.destination, so proxy the ctx to redirect
      // .destination to our tap node; superdough then handles note-off (ramps node.gain, calls stop).
      const ctx = getAudioContext();
      const note = value?.note ?? 'c3';
      const midi = typeof note === 'number' ? note : noteToMidi(note);
      const out = ctx.createGain();
      const proxied = new Proxy(ctx, {
        get(target, prop) {
          if (prop === 'destination') return out;
          const v = target[prop];
          return typeof v === 'function' ? v.bind(target) : v;
        },
      });
      const stop = startPresetNote(proxied, preset, midi, time);
      return { node: out, stop };
    }, { type: 'soundfont', prebake: false, fonts: [] });
  });
}

await Promise.all([
  registerSoundfont('https://raw.githubusercontent.com/lmorchard/starnet/main/audio-content/soundfonts/GeneralUser-GS.sf2', 'gus_'), // gus
  registerSoundfont('https://raw.githubusercontent.com/lmorchard/starnet/main/audio-content/soundfonts/MuseScore-Pad.sf2', 'msgpad_'), // msgpad
  registerSoundfont('https://raw.githubusercontent.com/lmorchard/starnet/main/audio-content/soundfonts/MuseScore-Lead.sf2', 'msglead_'), // msglead
  registerSoundfont('https://raw.githubusercontent.com/lmorchard/starnet/main/audio-content/soundfonts/MuseScore-FX.sf2', 'msgfx_'), // msgfx
  registerSoundfont('https://raw.githubusercontent.com/lmorchard/starnet/main/audio-content/soundfonts/MuseScore-Bass.sf2', 'msgbass_'), // msgbass
  registerSoundfont('https://raw.githubusercontent.com/lmorchard/starnet/main/audio-content/soundfonts/MuseScore-Keys.sf2', 'msgkeys_'), // msgkeys
  registerSoundfont('https://raw.githubusercontent.com/lmorchard/starnet/main/audio-content/soundfonts/MuseScore-Organ.sf2', 'msgorg_'), // msgorg
  registerSoundfont('https://raw.githubusercontent.com/lmorchard/starnet/main/audio-content/soundfonts/MuseScore-Guitar.sf2', 'msggtr_'), // msggtr
  registerSoundfont('https://raw.githubusercontent.com/lmorchard/starnet/main/audio-content/soundfonts/MuseScore-Drums.sf2', 'msgdrum_'), // msgdrum
]);

// ── 2. Signals: stub gameProgress / gameThreat so reactive songs play + react while authoring ──
// Keep this list in sync with js/audio/signal-registry.js (currently: gameProgress, gameThreat).
// Assigned onto `window.` — NOT `let` (a let binding wouldn't be visible to the separately-evaluated
// song, and bare assignment throws under strict mode). Default is sliders (draggable widgets);
// swap to sweep or mouse below for hands-free / pointer control.

// --- sliders (default): draggable widgets for deliberate values --------------------------------
window.gameProgress = slider(0.5, 0, 1)
window.gameThreat   = slider(0.5, 0, 1)

// --- auto-sweep: phased sines drift the two axes across their range hands-free ------------------
// window.gameProgress = sine.range(0, 1).slow(64)
// window.gameThreat   = sine.range(0, 1).slow(37)

// --- mouse drive: X = gameProgress, Y = gameThreat (move the pointer to steer) ------------------
// window.gameProgress = mousex
// window.gameThreat   = mousey
