// @ts-check
// Generates audio-content/strudel-prebake.js from the soundfont manifest.
// Run via: make gen-prebake
// Do NOT edit the generated file by hand — edit the manifest or this generator.

import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { writeFileSync } from "node:fs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");

// Import the manifest using createRequire so we can resolve it absolutely.
// (The manifest uses ESM export; import() works fine from a Node script.)
const { SOUNDFONTS } = await import(
  resolve(projectRoot, "audio-content/soundfonts/manifest.js")
);

// ── Static preamble ───────────────────────────────────────────────────────────

const HEADER = `\
// Starnet — strudel.cc PREBAKE  (one-paste authoring block)
// =====================================================================================
// AUTO-GENERATED by \`make gen-prebake\` from audio-content/soundfonts/manifest.js.
// Do not edit by hand — edit the manifest or scripts/gen-prebake.js instead.
//
// Paste this ONCE into strudel.cc → Settings → "prebake" (the script that runs before every
// song). It sets up BOTH halves of the game's sound world so a Starnet song copied straight out
// of the repo plays UNCHANGED in the editor:
//
//   1. Instruments — the game's soundfont presets per font (gus_*, msg_*, …).
//      Each is a DISTINCT set, NOT strudel's built-in gm_*; do not substitute.
//   2. Signals — the live game variables \`gameProgress\` / \`gameThreat\`, stubbed here as sliders
//      you drag to hear a song react.
//
// In the game these same names are provided by the engine (js/audio/strudel/soundfont.js registers
// the identical presets; js/audio/strudel/signal-bridge.js injects the same signals), so song files
// carry no setup of their own — this prebake is the editor-side mirror of that contract.`;

// ── Firefox cancelAndHoldAtTime polyfill (verbatim) ──────────────────────────

const FIREFOX_SHIM = `\
// ── 0. Firefox soundfont-release fix ──
// Firefox does not implement AudioParam.cancelAndHoldAtTime, which the SF2 player calls on every
// soundfont note-off. Without it note-offs throw in Firefox → soundfont voices never release (notes
// ring forever, voices pile up). Polyfill it (hold-current-value) before anything plays. No-op in
// Chrome, and no-op in the game (the engine's runtime installs the same shim). Mirrors runtime.js.
if (typeof AudioParam !== 'undefined' && typeof AudioParam.prototype.cancelAndHoldAtTime !== 'function') {
  AudioParam.prototype.cancelAndHoldAtTime = function (t) {
    const held = this.value;
    try { this.cancelScheduledValues(t); } catch (_) { /* ignore */ }
    try { this.setValueAtTime(held, t); } catch (_) { /* ignore */ }
    return this;
  };
}`;

// ── Signal stubs (verbatim) ───────────────────────────────────────────────────

const SIGNAL_STUBS = `\
// ── ${SOUNDFONTS.length + 1}. Signals: stub gameProgress / gameThreat so reactive songs play + react while authoring ──
// Keep this list in sync with js/audio/signal-registry.js (currently: gameProgress, gameThreat).
// Assigned onto \`window.\` — NOT \`let\` (a let binding wouldn't be visible to the separately-evaluated
// song, and bare assignment throws under strict mode). Default is sliders (draggable widgets);
// swap to sweep or mouse below for hands-free / pointer control.

// --- sliders (default): draggable widgets for deliberate values --------------------------------
window.gameProgress = slider(0.5, 0, 1)
window.gameThreat   = slider(0.5, 0, 1)

// --- auto-sweep: phased sines drift the two axes across their range hands-free ------------------
// window.gameProgress = sine.range(0, 1).slow(64)
// window.gameThreat   = sine.range(0, 1).slow(37)

// --- mouse drive: X = gameProgress, Y = gameThreat (move the pointer to steer) ------------------
// window.gameProgress = mousex
// window.gameThreat   = mousey`;

// ── Per-font soundfont block generator ───────────────────────────────────────

/**
 * Render one soundfont loading block for a manifest entry.
 * @param {{ prefix: string, host?: string }} entry
 * @param {number} idx  1-based index (for the section header number)
 * @returns {string}
 */
function renderFontBlock(entry, idx) {
  const { prefix, host } = entry;
  if (!host) throw new Error(`[gen-prebake] manifest entry '${prefix}' has no host URL`);

  // Derive a readable font label from the prefix for the comment header.
  // e.g. "gus_" → "gus", "msg_" → "msg" (simple; keep it terse).
  const label = prefix.replace(/_$/, "");

  return `\
// ── ${idx}. Instruments (${label}): load soundfont + register the ${prefix}* names ──
// Loads the full authoring SF2 (CORS-enabled host), so the sound set is byte-identical to what
// composers work with. The naming (sanitize + dedup) and the note trigger MIRROR
// js/audio/strudel/soundfont.js exactly; keep them in sync if that file changes.
// \`fonts: []\` is required so strudel.cc's soundfont UI can render the entry (it reads
// options.fonts.length); our trigger closes over \`preset\`, so the array itself is unused for audio.
await loadSoundfont(${JSON.stringify(host)})
  .then((sf) => {
    const used = new Set();
    sf.presets.forEach((preset, i) => {
      const cleaned = String(preset.header?.name || '').toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
      let name = ${JSON.stringify(prefix)} + (cleaned || 'preset_' + i);
      if (used.has(name)) { const base = name; let n = 2; while (used.has(name)) name = base + '_' + n++; }
      used.add(name);
      registerSound(name, (time, value) => {
        const ctx = getAudioContext();
        const note = value?.note ?? 'c3';
        const midi = typeof note === 'number' ? note : noteToMidi(note);
        const stop = startPresetNote(ctx, preset, midi, time);
        stop(time + (typeof value?.duration === 'number' ? value.duration : 0.5));
        return { node: undefined, stop };
      }, { type: 'soundfont', prebake: false, fonts: [] });
    });
  });`;
}

// ── Assemble and write ────────────────────────────────────────────────────────

const fontBlocks = SOUNDFONTS.map((entry, i) => renderFontBlock(entry, i + 1));

const output = [HEADER, "", FIREFOX_SHIM, "", fontBlocks.join("\n\n"), "", SIGNAL_STUBS, ""].join("\n");

const outPath = resolve(projectRoot, "audio-content/strudel-prebake.js");
writeFileSync(outPath, output, "utf8");
process.stderr.write(`gen-prebake: wrote ${outPath}\n`);
